### ISSUE TITLE
Need to free 2GB aditional space

### ISSUE THREAD

**Issue by schwarld** [rolandoislas/SmiteInstallScriptPOL#1]
I installed successfully the launcher and I can log in but it wont download the game. It says I need 2GB of aditional space but I have a lot more than that.
![selection_002](https://cloud.githubusercontent.com/assets/16889012/12568452/5001340e-c3c6-11e5-870a-7344f9ac81bb.png)

**Comment by opencma** [comment]
The full install is somewhere between 7 and 8 gigabytes. The installer may be correct and cannot find enough disk space.
