### ISSUE TITLE
Error with registering xaudio2_7.dll

### ISSUE THREAD

**Issue by ghost** [rolandoislas/SmiteInstallScriptPOL#2]
Every other part of this script had worked fine until this point.
Here's the error:

```
02/17/16 21:22:12 - [POL_Wine] Message: Running wine-1.8.1 regsvr32 xaudio2_6.dll (Working directory : /home/zishyy/.PlayOnLinux/ressources)
regsvr32: Successfully registered DLL 'xaudio2_6.dll'
02/17/16 21:22:12 - [POL_Wine] Message: Wine return: 0
02/17/16 21:22:12 - [POL_Wine] Message: Running wine-1.8.1 regsvr32 xaudio2_7.dll (Working directory : /home/zishyy/.PlayOnLinux/ressources)
err:module:load_builtin_dll failed to load .so lib for builtin L"xaudio2_7.dll": libopenal.so.1: cannot open shared object file: No such file or directory
regsvr32: Failed to load DLL 'xaudio2_7.dll'
02/17/16 21:22:12 - [POL_Wine] Message: Wine return: 3
02/17/16 21:22:12 - [source] Fatal: Error 3 registering DLL /home/zishyy/.PlayOnLinux//wineprefix/Smite/drive_c/windows/system32/xaudio2_7.dll
```

The file itself does seem to exist however:
![screenshot from 2016-02-17 21-34-54](https://cloud.githubusercontent.com/assets/17302993/13125635/8971ea94-d5be-11e5-8d44-c941428c7b84.png)

This is on Manjaro Linux 15.12 64x, with PlayOnLinux 4.2.10

**Comment by opencma** [comment]
Do you have the `wine:i386` package installed?

You might want to go more specific and install `libopenal1:i386` but the wine package guarantees other dependencies are met, should they be required.

**Comment by ghost** [comment]
Thanks, installing openal seems to have done it and I can successfully install now. Thanks!
