### ISSUE TITLE
Download seems to be corrupted 

### ISSUE THREAD

**Issue by amirping** [rolandoislas/SmiteInstallScriptPOL#4]
i got problem after run the scripte with  POL on Debain 8 
"Download seems to be corrupted  retry ? "
and this is the log file 

[log Smite.txt](https://github.com/rolandoislas/SmiteInstallScriptPOL/files/151749/log.Smite.txt)

**Comment by opencma** [comment]
Hi-Rez changes the installer constantly thus changing the checksum. Download the installer and choose the local install option.
