### ISSUE TITLE
Install script failing for me

### ISSUE THREAD

**Issue by jjungreithmeir** [rolandoislas/SmiteInstallScriptPOL#7]
Hi,

I've tried to use the install script but it fails at a certain point. I included the SMITE.log file if that helps. I tried searching for the error but I didn't manage to find anything.
[SMITE_log.txt](https://github.com/rolandoislas/SmiteInstallScriptPOL/files/199978/SMITE_log.txt)

**Comment by opencma** [comment]
See #2.

**Comment by jjungreithmeir** [comment]
I had openal installed but lib32-openal was missing. After installing the missing package I was able to install Smite. Thank you for your quick response and the awesome script!

**Comment by jjungreithmeir** [comment]
Sorry to ask again but I have encountered another problem. After installing the lauchner it tries to update and is stuck in a loop. You've mentioned that on the main site of the repository and recommended to use xterm. I left the field blank and xterm opened itself but I still encountered the loop. I tried it again with xfce4-terminal but it still opened xterm.

**Comment by opencma** [comment]
Would you post your logs for the Smite prefix? The terminal variable fix seemed to work in other cases, but running on Arch might cause other issues. Also, when do see the terminal launched? In my testing, the updater seemed to make background calls and a terminal window was never present in the foreground.

**Comment by jjungreithmeir** [comment]
Sorry to say that but what do you mean by logs for the Smite prefix? I am quite unfamiliar with Wine and Playonlinux. And as you said the terminal is not visible during the update process.

**Comment by opencma** [comment]
PlayOnLinux should have the option to open the debugger. The log should be there.

**Comment by jjungreithmeir** [comment]
Here is the log file: 
[SMITE_log.txt](https://github.com/rolandoislas/SmiteInstallScriptPOL/files/201458/SMITE_log.txt)

**Comment by opencma** [comment]
From the Tools menu, there is the "PlayOnLinux Debugger" option. Launch that and a window will display with logs from all installers and virtual drives. Please post the log from the smite virtual drive.

**Comment by jjungreithmeir** [comment]
I am very sorry for attaching the wrong logfile. Here is the log of the Smite virtual drive: 
[playonlinux_log.txt](https://github.com/rolandoislas/SmiteInstallScriptPOL/files/202810/playonlinux_log.txt)

**Comment by opencma** [comment]
Arch Linux does not install all of Wine's dependencies by default. They are listed as optional but are required to run some software. Have a look at the dependency list for wine [here](https://www.archlinux.org/packages/multilib/x86_64/wine/). From the log, it would appear that you need libpng and ncurses at the minimum.

**Comment by jjungreithmeir** [comment]
Sadly I had both of them already installed(also multilib packages) and after reinstalling them nothing changed, still got the loop.

**Comment by opencma** [comment]
Did you install them after posting the log?

**Comment by opencma** [comment]
The wine prefix needs the 32-bit variant of ncurses, lib32-ncurses.

**Comment by jjungreithmeir** [comment]
ncurses, lib32-ncurses, lib32-libpng and libpng were installed before I posted the log. I just reinstalled them a few minutes ago to be sure and nothing changed.

**Comment by opencma** [comment]
Have a look at [this forum thread](https://forum.winehq.org/viewtopic.php?f=8&t=25293). One possible issue is that a newer version of ncurses is installed and wine is looking for an older version.

**Comment by jjungreithmeir** [comment]
That was the problem, thank you for your patience.
