### ISSUE TITLE
Can't reach the Server

### ISSUE THREAD

**Issue by Yaksinikos** [rolandoislas/SmiteInstallScriptPOL#8]
After Patch 3.5 Smite don't work anymore :/ (security-patch)
After the game is started, there came up a login window with "cant reach the server"
:/

**Comment by opencma** [comment]
Please post the log.

**Comment by Yaksinikos** [comment]
I've got it after reinstall (2 times :laughing:)
I've installed the game again, over the old-one, worked fine!
Just played.
