### ISSUE TITLE
Crash when trying to play, prerequisites failed to install. 

### ISSUE THREAD

**Issue by teo3n** [rolandoislas/SmiteInstallScriptPOL#9]
So yeah. The prerequisites failed and every time I press "Play" it crashes and gives that UE3 crash report -window. "VCRedist x86 failed to install"

**Comment by opencma** [comment]
Please, post your [logs](https://github.com/rolandoislas/SmiteInstallScriptPOL/issues/7#issuecomment-205082323).

**Comment by teo3n** [comment]
Sorry it took me a while to check this thread again. I was able to fix it by manually forcing the installation and now it works.
